version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: infection/infection
    versions:
    - 0.22.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.82
    - 0.12.84
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.4
